# Generated by Django 4.2.3 on 2023-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='type_gun',
            field=models.IntegerField(),
        ),
    ]
