# Generated by Django 4.2.3 on 2023-08-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0002_alter_skin_type_gun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_gun',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
