# Generated by Django 4.2.3 on 2023-08-02 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0003_alter_type_gun_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_gun',
            name='id',
            field=models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
