# Generated by Django 4.2.3 on 2023-08-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0005_rename_float_gun_skin_price_remove_skin_type_gun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='assetid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
