# Generated by Django 4.2.4 on 2023-08-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0007_auto_20230811_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesteam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
